defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: currmap_development

test:
  <<: *defaults
  database: currmap_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: flame.mongohq.com
  port: 27075
  username: mongodb
  password: gogomongo
  database: currmap