development:
  solr:
    hostname: localhost
    port: 8982
    min_memory: 512M
    max_memory: 1G
test:
  solr:
    hostname: localhost
    port: 8983
    log_level: OFF
production:
  solr:
    hostname: 68.68.99.19
    port: 8983
    log_level: WARNING
  auto_commit_after_request: true