development:
  solr:
    hostname: localhost
    port: 8982
    min_memory: 512M
    max_memory: 1G
test:
  solr:
    hostname: localhost
    port: 8983
    log_level: OFF
production:
  solr:
    hostname: http://rafd.xen.prgmr.com/
    port: 8983
    path: /solr/currmap
    log_level: WARNING
    #solr_home: /some/path
  #master_solr:
  #  hostname: localhost
  #  port: 8982
  #  path: /solr
  auto_commit_after_request: true